import type { Equipment, Ingredient, Recipe } from './types.js';

// Versioned starter content using normalized ingredient and equipment identifiers.
export const equipment: Equipment[] = [
  { id: 'stove', name: 'Stove' },
  { id: 'oven', name: 'Oven' },
  { id: 'microwave', name: 'Microwave' },
  { id: 'blender', name: 'Blender' },
  { id: 'pan', name: 'Pan' },
  { id: 'pot', name: 'Pot' },
];

export const ingredients: Ingredient[] = [
  { canonicalName: 'beef', displayName: 'Beef', aliases: ['ground beef', 'steak'] },
  { canonicalName: 'pork', displayName: 'Pork', aliases: ['ground pork', 'pork chops'] },
  { canonicalName: 'cumin', displayName: 'Cumin', aliases: ['jeera'] },
  { canonicalName: 'coriander', displayName: 'Coriander', aliases: ['dhania', 'cilantro'] },
  { canonicalName: 'turmeric', displayName: 'Turmeric', aliases: ['haldi'] },
  { canonicalName: 'ginger', displayName: 'Ginger', aliases: ['adrak'] },
  { canonicalName: 'basil', displayName: 'Basil', aliases: ['sweet basil'] },
  { canonicalName: 'mozzarella', displayName: 'Mozzarella', aliases: ['mozzarella cheese'] },
  { canonicalName: 'soy milk', displayName: 'Soy milk', aliases: ['soymilk'] },
  { canonicalName: 'shrimp', displayName: 'Shrimp', aliases: ['prawns'] },
  { canonicalName: 'salmon', displayName: 'Salmon', aliases: [] },
  { canonicalName: 'sweet potato', displayName: 'Sweet potato', aliases: ['sweet potatoes'] },
  { canonicalName: 'zucchini', displayName: 'Zucchini', aliases: ['courgette'] },
  { canonicalName: 'eggplant', displayName: 'Eggplant', aliases: ['aubergine', 'baingan'] },
  { canonicalName: 'garam masala', displayName: 'Garam Masala', aliases: [] },
  { canonicalName: 'mustard seeds', displayName: 'Mustard Seeds', aliases: ['rai'] },
  { canonicalName: 'chili powder', displayName: 'Chili Powder', aliases: ['red chili'] },
  { canonicalName: 'butter', displayName: 'Butter', aliases: [] },
  { canonicalName: 'cream', displayName: 'Cream', aliases: ['heavy cream', 'malai'] },
  { canonicalName: 'yogurt', displayName: 'Yogurt', aliases: ['curd', 'dahi'] },
  { canonicalName: 'egg', displayName: 'Eggs', aliases: ['eggs'] },
  { canonicalName: 'rice', displayName: 'Rice', aliases: [] },
  { canonicalName: 'onion', displayName: 'Onion', aliases: ['red onion'] },
  { canonicalName: 'tomato', displayName: 'Tomatoes', aliases: ['tomatoes'] },
  { canonicalName: 'chicken', displayName: 'Chicken', aliases: ['chicken breast'] },
  { canonicalName: 'beans', displayName: 'Beans', aliases: ['black beans', 'kidney beans'] },
  { canonicalName: 'pasta', displayName: 'Pasta', aliases: ['spaghetti'] },
  { canonicalName: 'spinach', displayName: 'Spinach', aliases: [] },
  { canonicalName: 'banana', displayName: 'Banana', aliases: [] },
  { canonicalName: 'oats', displayName: 'Oats', aliases: ['rolled oats', 'oatmeal'] },
  { canonicalName: 'bread', displayName: 'Bread', aliases: ['toast'] },
  { canonicalName: 'cheese', displayName: 'Cheese', aliases: [] },
  { canonicalName: 'yogurt', displayName: 'Greek yogurt', aliases: ['greek yogurt'] },
  { canonicalName: 'bell pepper', displayName: 'Bell pepper', aliases: ['pepper'] },
  { canonicalName: 'lemon', displayName: 'Lemon', aliases: [] },
  { canonicalName: 'soy sauce', displayName: 'Soy sauce', aliases: ['soya sauce'] },
  { canonicalName: 'lentils', displayName: 'Lentils', aliases: ['dal', 'dhal'] },
  { canonicalName: 'potato', displayName: 'Potato', aliases: ['potatoes'] },
  { canonicalName: 'carrot', displayName: 'Carrot', aliases: ['carrots'] },
  { canonicalName: 'cucumber', displayName: 'Cucumber', aliases: [] },
  { canonicalName: 'tuna', displayName: 'Tuna', aliases: ['canned tuna'] },
  { canonicalName: 'chickpeas', displayName: 'Chickpeas', aliases: ['garbanzo beans'] },
  { canonicalName: 'milk', displayName: 'Milk', aliases: [] },
  { canonicalName: 'peanut butter', displayName: 'Peanut butter', aliases: ['peanutbutter'] },
  { canonicalName: 'garlic', displayName: 'Garlic', aliases: [] },
  { canonicalName: 'mushroom', displayName: 'Mushrooms', aliases: ['mushrooms'] },
  { canonicalName: 'broccoli', displayName: 'Broccoli', aliases: [] },
  { canonicalName: 'corn', displayName: 'Corn', aliases: [] },
  { canonicalName: 'peas', displayName: 'Peas', aliases: [] },
  { canonicalName: 'tortilla', displayName: 'Tortilla', aliases: ['wrap'] },
  { canonicalName: 'avocado', displayName: 'Avocado', aliases: [] },
  { canonicalName: 'tofu', displayName: 'Tofu', aliases: [] },
  { canonicalName: 'cabbage', displayName: 'Cabbage', aliases: [] },
  { canonicalName: 'apple', displayName: 'Apple', aliases: ['apples'] },
  { canonicalName: 'honey', displayName: 'Honey', aliases: [] },
  { canonicalName: 'flour', displayName: 'Flour', aliases: [] },
  { canonicalName: 'coconut milk', displayName: 'Coconut milk', aliases: [] },
  { canonicalName: 'paneer', displayName: 'Paneer', aliases: [] },
  { canonicalName: 'lettuce', displayName: 'Lettuce', aliases: [] },
];

export const recipes: Recipe[] = [
  {"id":"zucchini-noodle-salad","title":"Zucchini Noodle Salad","description":"A crisp, raw zucchini noodle salad with a bright lemon dressing.","ingredients":[{"name":"zucchini","quantity":"1, spiralized"},{"name":"tomato","quantity":"1, diced"},{"name":"lemon","quantity":"1/2"},{"name":"basil","quantity":"1 handful"}],"equipment":[],"tags":["weight-loss","healthy"],"difficulty":"easy","timeMinutes":10,"instructions": []},
  {"id":"paneer-tikka-masala","title":"Paneer Tikka Masala","description":"A delicious and authentic take on Paneer Tikka Masala.","ingredients":[{"name":"paneer","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"yogurt","quantity":"1 serving"},{"name":"garam masala","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare paneer, tomato, yogurt, garam masala. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":23},
  {"id":"dal-tadka","title":"Dal Tadka","description":"A delicious and authentic take on Dal Tadka.","ingredients":[{"name":"lentils","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"},{"name":"cumin","quantity":"1 serving"},{"name":"garlic","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare lentils, onion, cumin, garlic. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"medium","timeMinutes":24},
  {"id":"aloo-gobi","title":"Aloo Gobi","description":"A delicious and authentic take on Aloo Gobi.","ingredients":[{"name":"potato","quantity":"1 serving"},{"name":"broccoli","quantity":"1 serving"},{"name":"turmeric","quantity":"1 serving"},{"name":"cumin","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare potato, broccoli, turmeric, cumin.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":25},
  {"id":"palak-paneer","title":"Palak Paneer","description":"A delicious and authentic take on Palak Paneer.","ingredients":[{"name":"spinach","quantity":"1 serving"},{"name":"paneer","quantity":"1 serving"},{"name":"garlic","quantity":"1 serving"},{"name":"cream","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare spinach, paneer, garlic, cream. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":26},
  {"id":"chana-masala","title":"Chana Masala","description":"A delicious and authentic take on Chana Masala.","ingredients":[{"name":"chickpeas","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"},{"name":"garam masala","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare chickpeas, tomato, onion, garam masala. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"medium","timeMinutes":27},
  {"id":"jeera-rice","title":"Jeera Rice","description":"A delicious and authentic take on Jeera Rice.","ingredients":[{"name":"rice","quantity":"1 serving"},{"name":"cumin","quantity":"1 serving"},{"name":"butter","quantity":"1 serving"},{"name":"coriander","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare rice, cumin, butter, coriander. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":28},
  {"id":"egg-curry","title":"Egg Curry","description":"A delicious and authentic take on Egg Curry.","ingredients":[{"name":"egg","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"},{"name":"garam masala","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare egg, tomato, onion, garam masala.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":29},
  {"id":"baingan-bharta","title":"Baingan Bharta","description":"A delicious and authentic take on Baingan Bharta.","ingredients":[{"name":"eggplant","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"},{"name":"garlic","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare eggplant, tomato, onion, garlic. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"medium","timeMinutes":30},
  {"id":"mushroom-matar","title":"Mushroom Matar","description":"A delicious and authentic take on Mushroom Matar.","ingredients":[{"name":"mushroom","quantity":"1 serving"},{"name":"peas","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare mushroom, peas, onion, tomato. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":31},
  {"id":"chicken-korma","title":"Chicken Korma","description":"A delicious and authentic take on Chicken Korma.","ingredients":[{"name":"chicken","quantity":"1 serving"},{"name":"yogurt","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"},{"name":"coriander","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare chicken, yogurt, onion, coriander. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","high-protein"],"difficulty":"easy","timeMinutes":32},
  {"id":"fish-curry","title":"Fish Curry","description":"A delicious and authentic take on Fish Curry.","ingredients":[{"name":"salmon","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"coconut milk","quantity":"1 serving"},{"name":"turmeric","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare salmon, tomato, coconut milk, turmeric.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","high-protein"],"difficulty":"medium","timeMinutes":33},
  {"id":"vegetable-biryani","title":"Vegetable Biryani","description":"A delicious and authentic take on Vegetable Biryani.","ingredients":[{"name":"rice","quantity":"1 serving"},{"name":"carrot","quantity":"1 serving"},{"name":"beans","quantity":"1 serving"},{"name":"garam masala","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare rice, carrot, beans, garam masala. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":34},
  {"id":"bhindi-masala","title":"Bhindi Masala","description":"A delicious and authentic take on Bhindi Masala.","ingredients":[{"name":"zucchini","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"cumin","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare zucchini, onion, tomato, cumin. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":35},
  {"id":"rajma","title":"Rajma","description":"A delicious and authentic take on Rajma.","ingredients":[{"name":"beans","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"},{"name":"garam masala","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare beans, tomato, onion, garam masala. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"medium","timeMinutes":36},
  {"id":"chicken-madras","title":"Chicken Madras","description":"A delicious and authentic take on Chicken Madras.","ingredients":[{"name":"chicken","quantity":"1 serving"},{"name":"chili powder","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"mustard seeds","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare chicken, chili powder, tomato, mustard seeds.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","high-protein"],"difficulty":"easy","timeMinutes":37},
  {"id":"prawn-curry","title":"Prawn Curry","description":"A delicious and authentic take on Prawn Curry.","ingredients":[{"name":"shrimp","quantity":"1 serving"},{"name":"coconut milk","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"},{"name":"turmeric","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare shrimp, coconut milk, onion, turmeric. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":38},
  {"id":"tofu-tikka","title":"Tofu Tikka","description":"A delicious and authentic take on Tofu Tikka.","ingredients":[{"name":"tofu","quantity":"1 serving"},{"name":"yogurt","quantity":"1 serving"},{"name":"garam masala","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare tofu, yogurt, garam masala, onion. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"medium","timeMinutes":39},
  {"id":"aloo-matar","title":"Aloo Matar","description":"A delicious and authentic take on Aloo Matar.","ingredients":[{"name":"potato","quantity":"1 serving"},{"name":"peas","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"cumin","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare potato, peas, tomato, cumin. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":40},
  {"id":"matar-paneer","title":"Matar Paneer","description":"A delicious and authentic take on Matar Paneer.","ingredients":[{"name":"paneer","quantity":"1 serving"},{"name":"peas","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"garam masala","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare paneer, peas, tomato, garam masala.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":41},
  {"id":"keema-matar","title":"Keema Matar","description":"A delicious and authentic take on Keema Matar.","ingredients":[{"name":"beef","quantity":"1 serving"},{"name":"peas","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare beef, peas, onion, tomato. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","high-protein"],"difficulty":"medium","timeMinutes":42},
  {"id":"chicken-65","title":"Chicken 65","description":"A delicious and authentic take on Chicken 65.","ingredients":[{"name":"chicken","quantity":"1 serving"},{"name":"yogurt","quantity":"1 serving"},{"name":"chili powder","quantity":"1 serving"},{"name":"garlic","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare chicken, yogurt, chili powder, garlic. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","high-protein"],"difficulty":"easy","timeMinutes":43},
  {"id":"dal-makhani","title":"Dal Makhani","description":"A delicious and authentic take on Dal Makhani.","ingredients":[{"name":"lentils","quantity":"1 serving"},{"name":"beans","quantity":"1 serving"},{"name":"butter","quantity":"1 serving"},{"name":"cream","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare lentils, beans, butter, cream. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":44},
  {"id":"south-indian-lemon-rice","title":"South Indian Lemon Rice","description":"A delicious and authentic take on South Indian Lemon Rice.","ingredients":[{"name":"rice","quantity":"1 serving"},{"name":"lemon","quantity":"1 serving"},{"name":"mustard seeds","quantity":"1 serving"},{"name":"peanut butter","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare rice, lemon, mustard seeds, peanut butter.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","healthy"],"difficulty":"medium","timeMinutes":15},
  {"id":"chicken-chettinad","title":"Chicken Chettinad","description":"A delicious and authentic take on Chicken Chettinad.","ingredients":[{"name":"chicken","quantity":"1 serving"},{"name":"coconut milk","quantity":"1 serving"},{"name":"coriander","quantity":"1 serving"},{"name":"chili powder","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare chicken, coconut milk, coriander, chili powder. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","high-protein"],"difficulty":"easy","timeMinutes":16},
  {"id":"turkey-lettuce-wraps","title":"Turkey Lettuce Wraps","description":"Lean protein wrapped in crisp, refreshing lettuce leaves.","ingredients":[{"name":"chicken","quantity":"1 breast, minced"},{"name":"lettuce","quantity":"4 large leaves"},{"name":"onion","quantity":"1/4, diced"},{"name":"soy sauce","quantity":"1 tbsp"}],"equipment":["pan","stove"],"tags":["weight-loss","high-protein"],"difficulty":"easy","timeMinutes":12,"instructions": []},
  {"id":"masala-omelette","title":"Masala Omelette","description":"A delicious and authentic take on Masala Omelette.","ingredients":[{"name":"egg","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"chili powder","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare egg, onion, tomato, chili powder. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"medium","timeMinutes":18},
  {"id":"curd-rice","title":"Curd Rice","description":"A delicious and authentic take on Curd Rice.","ingredients":[{"name":"rice","quantity":"1 serving"},{"name":"yogurt","quantity":"1 serving"},{"name":"mustard seeds","quantity":"1 serving"},{"name":"cucumber","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare rice, yogurt, mustard seeds, cucumber.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":19},
  {"id":"sweet-potato-tikki","title":"Sweet Potato Tikki","description":"A delicious and authentic take on Sweet Potato Tikki.","ingredients":[{"name":"sweet potato","quantity":"1 serving"},{"name":"cumin","quantity":"1 serving"},{"name":"coriander","quantity":"1 serving"},{"name":"bread","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare sweet potato, cumin, coriander, bread. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":20},
  {"id":"chicken-tikka-salad","title":"Chicken Tikka Salad","description":"A delicious and authentic take on Chicken Tikka Salad.","ingredients":[{"name":"chicken","quantity":"1 serving"},{"name":"lettuce","quantity":"1 serving"},{"name":"yogurt","quantity":"1 serving"},{"name":"cucumber","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare chicken, lettuce, yogurt, cucumber. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","high-protein"],"difficulty":"medium","timeMinutes":21},
  {"id":"spicy-tomato-broth","title":"Spicy Tomato Broth","description":"A fiery, metabolism-boosting clear soup.","ingredients":[{"name":"tomato","quantity":"3, pureed"},{"name":"garlic","quantity":"1 clove"},{"name":"chili powder","quantity":"1 tsp"},{"name":"coriander","quantity":"1 tbsp, fresh"}],"equipment":["pot","stove"],"tags":["weight-loss","healthy"],"difficulty":"easy","timeMinutes":15,"instructions": []},
  {"id":"paneer-bhurji","title":"Paneer Bhurji","description":"A delicious and authentic take on Paneer Bhurji.","ingredients":[{"name":"paneer","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"bell pepper","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare paneer, onion, tomato, bell pepper.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":23},
  {"id":"spaghetti-bolognese","title":"Spaghetti Bolognese","description":"A delicious and authentic take on Spaghetti Bolognese.","ingredients":[{"name":"pasta","quantity":"1 serving"},{"name":"beef","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare pasta, beef, tomato, onion. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","high-protein"],"difficulty":"medium","timeMinutes":24},
  {"id":"cauliflower-rice-bowl","title":"Cauliflower Rice Bowl","description":"A low-carb alternative to a rice bowl loaded with greens.","ingredients":[{"name":"cabbage","quantity":"1 cup, finely riced"},{"name":"spinach","quantity":"2 handfuls"},{"name":"chicken","quantity":"1 breast, grilled"},{"name":"lemon","quantity":"1/2"}],"equipment":["pan","stove"],"tags":["weight-loss","high-protein"],"difficulty":"easy","timeMinutes":15,"instructions": []},
  {"id":"caprese-salad","title":"Caprese Salad","description":"A delicious and authentic take on Caprese Salad.","ingredients":[{"name":"tomato","quantity":"1 serving"},{"name":"mozzarella","quantity":"1 serving"},{"name":"basil","quantity":"1 serving"},{"name":"lemon","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare tomato, mozzarella, basil, lemon. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":26},
  {"id":"beef-tacos","title":"Beef Tacos","description":"A delicious and authentic take on Beef Tacos.","ingredients":[{"name":"beef","quantity":"1 serving"},{"name":"tortilla","quantity":"1 serving"},{"name":"cheese","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare beef, tortilla, cheese, tomato.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","high-protein"],"difficulty":"medium","timeMinutes":27},
  {"id":"chicken-fajitas","title":"Chicken Fajitas","description":"A delicious and authentic take on Chicken Fajitas.","ingredients":[{"name":"chicken","quantity":"1 serving"},{"name":"bell pepper","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"},{"name":"tortilla","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare chicken, bell pepper, onion, tortilla. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","high-protein"],"difficulty":"easy","timeMinutes":28},
  {"id":"broccoli-garlic-stir-fry","title":"Broccoli Garlic Stir-Fry","description":"A huge volume of vegetables with minimal calories.","ingredients":[{"name":"broccoli","quantity":"2 cups, chopped"},{"name":"garlic","quantity":"2 cloves, minced"},{"name":"soy sauce","quantity":"1 tbsp"},{"name":"mushroom","quantity":"1/2 cup, sliced"}],"equipment":["pan","stove"],"tags":["weight-loss","healthy"],"difficulty":"easy","timeMinutes":10,"instructions": []},
  {"id":"salmon-teriyaki","title":"Salmon Teriyaki","description":"A delicious and authentic take on Salmon Teriyaki.","ingredients":[{"name":"salmon","quantity":"1 serving"},{"name":"soy sauce","quantity":"1 serving"},{"name":"rice","quantity":"1 serving"},{"name":"broccoli","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare salmon, soy sauce, rice, broccoli. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","high-protein"],"difficulty":"medium","timeMinutes":30},
  {"id":"beef-stir-fry","title":"Beef Stir Fry","description":"A delicious and authentic take on Beef Stir Fry.","ingredients":[{"name":"beef","quantity":"1 serving"},{"name":"broccoli","quantity":"1 serving"},{"name":"soy sauce","quantity":"1 serving"},{"name":"garlic","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare beef, broccoli, soy sauce, garlic.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","high-protein"],"difficulty":"easy","timeMinutes":31},
  {"id":"margherita-pizza-toast","title":"Margherita Pizza Toast","description":"A delicious and authentic take on Margherita Pizza Toast.","ingredients":[{"name":"bread","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"mozzarella","quantity":"1 serving"},{"name":"basil","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare bread, tomato, mozzarella, basil. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":32},
  {"id":"chicken-caesar-salad","title":"Chicken Caesar Salad","description":"A delicious and authentic take on Chicken Caesar Salad.","ingredients":[{"name":"chicken","quantity":"1 serving"},{"name":"lettuce","quantity":"1 serving"},{"name":"cheese","quantity":"1 serving"},{"name":"bread","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare chicken, lettuce, cheese, bread. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","high-protein"],"difficulty":"medium","timeMinutes":33},
  {"id":"cucumber-tomato-salad","title":"Cucumber Tomato Salad","description":"A refreshing, hydrating salad with zero cooking required.","ingredients":[{"name":"cucumber","quantity":"1, chopped"},{"name":"tomato","quantity":"2, chopped"},{"name":"onion","quantity":"1/4, finely diced"},{"name":"lemon","quantity":"1/2"}],"equipment":[],"tags":["weight-loss","healthy"],"difficulty":"easy","timeMinutes":5,"instructions": []},
  {"id":"lentil-cucumber-salad","title":"Lentil Cucumber Salad","description":"A fiber-rich salad that keeps you full for hours.","ingredients":[{"name":"lentils","quantity":"1/2 cup, cooked"},{"name":"cucumber","quantity":"1/2, diced"},{"name":"tomato","quantity":"1, diced"},{"name":"lemon","quantity":"1/2"}],"equipment":[],"tags":["weight-loss","healthy"],"difficulty":"easy","timeMinutes":5,"instructions": []},
  {"id":"zucchini-noodles","title":"Zucchini Noodles","description":"A delicious and authentic take on Zucchini Noodles.","ingredients":[{"name":"zucchini","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"garlic","quantity":"1 serving"},{"name":"mozzarella","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare zucchini, tomato, garlic, mozzarella. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"medium","timeMinutes":36},
  {"id":"baked-salmon","title":"Baked Salmon","description":"A delicious and authentic take on Baked Salmon.","ingredients":[{"name":"salmon","quantity":"1 serving"},{"name":"lemon","quantity":"1 serving"},{"name":"garlic","quantity":"1 serving"},{"name":"sweet potato","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare salmon, lemon, garlic, sweet potato. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","high-protein"],"difficulty":"easy","timeMinutes":37},
  {"id":"baked-lemon-cod","title":"Baked Lemon Fish","description":"A very lean, high-protein white fish bake.","ingredients":[{"name":"salmon","quantity":"1 fillet"},{"name":"lemon","quantity":"1/2, sliced"},{"name":"broccoli","quantity":"1 cup"},{"name":"garlic","quantity":"1 clove, minced"}],"equipment":["oven"],"tags":["weight-loss","high-protein"],"difficulty":"medium","timeMinutes":20,"instructions": []},
  {"id":"chicken-parmesan","title":"Chicken Parmesan","description":"A delicious and authentic take on Chicken Parmesan.","ingredients":[{"name":"chicken","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"mozzarella","quantity":"1 serving"},{"name":"bread","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare chicken, tomato, mozzarella, bread.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","high-protein"],"difficulty":"medium","timeMinutes":39},
  {"id":"beef-burger-bowls","title":"Beef Burger Bowls","description":"A delicious and authentic take on Beef Burger Bowls.","ingredients":[{"name":"beef","quantity":"1 serving"},{"name":"lettuce","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"cheese","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare beef, lettuce, tomato, cheese. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","high-protein"],"difficulty":"easy","timeMinutes":40},
  {"id":"spinach-tofu-scramble","title":"Spinach Tofu Scramble","description":"A vegan, low-calorie scramble packed with protein.","ingredients":[{"name":"tofu","quantity":"150g, crumbled"},{"name":"spinach","quantity":"2 cups"},{"name":"tomato","quantity":"1, diced"},{"name":"turmeric","quantity":"1 pinch"}],"equipment":["pan","stove"],"tags":["weight-loss","high-protein"],"difficulty":"easy","timeMinutes":10,"instructions": []},
  {"id":"shrimp-fried-rice","title":"Shrimp Fried Rice","description":"A delicious and authentic take on Shrimp Fried Rice.","ingredients":[{"name":"rice","quantity":"1 serving"},{"name":"shrimp","quantity":"1 serving"},{"name":"egg","quantity":"1 serving"},{"name":"peas","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare rice, shrimp, egg, peas. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"medium","timeMinutes":42},
  {"id":"tofu-pad-thai","title":"Tofu Pad Thai","description":"A delicious and authentic take on Tofu Pad Thai.","ingredients":[{"name":"pasta","quantity":"1 serving"},{"name":"tofu","quantity":"1 serving"},{"name":"egg","quantity":"1 serving"},{"name":"peanut butter","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare pasta, tofu, egg, peanut butter.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":43},
  {"id":"chicken-noodle-soup","title":"Chicken Noodle Soup","description":"A delicious and authentic take on Chicken Noodle Soup.","ingredients":[{"name":"chicken","quantity":"1 serving"},{"name":"pasta","quantity":"1 serving"},{"name":"carrot","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare chicken, pasta, carrot, onion. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","high-protein"],"difficulty":"easy","timeMinutes":44},
  {"id":"minestrone-soup","title":"Minestrone Soup","description":"A delicious and authentic take on Minestrone Soup.","ingredients":[{"name":"pasta","quantity":"1 serving"},{"name":"beans","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"zucchini","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare pasta, beans, tomato, zucchini. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"medium","timeMinutes":15},
  {"id":"eggplant-parmesan","title":"Eggplant Parmesan","description":"A delicious and authentic take on Eggplant Parmesan.","ingredients":[{"name":"eggplant","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"mozzarella","quantity":"1 serving"},{"name":"cheese","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare eggplant, tomato, mozzarella, cheese. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":16},
  {"id":"greek-salad","title":"Greek Salad","description":"A delicious and authentic take on Greek Salad.","ingredients":[{"name":"cucumber","quantity":"1 serving"},{"name":"tomato","quantity":"1 serving"},{"name":"onion","quantity":"1 serving"},{"name":"cheese","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare cucumber, tomato, onion, cheese.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":17},
  {"id":"chicken-quesadilla","title":"Chicken Quesadilla","description":"A delicious and authentic take on Chicken Quesadilla.","ingredients":[{"name":"chicken","quantity":"1 serving"},{"name":"tortilla","quantity":"1 serving"},{"name":"cheese","quantity":"1 serving"},{"name":"bell pepper","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare chicken, tortilla, cheese, bell pepper. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","high-protein"],"difficulty":"medium","timeMinutes":18},
  {"id":"beef-burrito-bowl","title":"Beef Burrito Bowl","description":"A delicious and authentic take on Beef Burrito Bowl.","ingredients":[{"name":"beef","quantity":"1 serving"},{"name":"rice","quantity":"1 serving"},{"name":"beans","quantity":"1 serving"},{"name":"corn","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare beef, rice, beans, corn. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","high-protein"],"difficulty":"easy","timeMinutes":19},
  {"id":"shrimp-tacos","title":"Shrimp Tacos","description":"A delicious and authentic take on Shrimp Tacos.","ingredients":[{"name":"shrimp","quantity":"1 serving"},{"name":"tortilla","quantity":"1 serving"},{"name":"cabbage","quantity":"1 serving"},{"name":"lemon","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare shrimp, tortilla, cabbage, lemon. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":20},
  {"id":"pork-dumpling-bowl","title":"Pork Dumpling Bowl","description":"A delicious and authentic take on Pork Dumpling Bowl.","ingredients":[{"name":"pork","quantity":"1 serving"},{"name":"cabbage","quantity":"1 serving"},{"name":"rice","quantity":"1 serving"},{"name":"soy sauce","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare pork, cabbage, rice, soy sauce.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","healthy"],"difficulty":"medium","timeMinutes":21},
  {"id":"basil-pesto-pasta","title":"Basil Pesto Pasta","description":"A delicious and authentic take on Basil Pesto Pasta.","ingredients":[{"name":"pasta","quantity":"1 serving"},{"name":"basil","quantity":"1 serving"},{"name":"garlic","quantity":"1 serving"},{"name":"cheese","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare pasta, basil, garlic, cheese. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":22},
  {"id":"tomato-basil-soup","title":"Tomato Basil Soup","description":"A delicious and authentic take on Tomato Basil Soup.","ingredients":[{"name":"tomato","quantity":"1 serving"},{"name":"basil","quantity":"1 serving"},{"name":"cream","quantity":"1 serving"},{"name":"garlic","quantity":"1 serving"}],"equipment":["pan","stove"],"instructions":["Prepare tomato, basil, cream, garlic. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":23},
  {"id":"clear-cabbage-soup","title":"Clear Cabbage Soup","description":"A highly filling, very low-calorie clear vegetable soup.","ingredients":[{"name":"cabbage","quantity":"2 cups, chopped"},{"name":"onion","quantity":"1/2, diced"},{"name":"tomato","quantity":"1, diced"},{"name":"garlic","quantity":"1 clove"}],"equipment":["pot","stove"],"tags":["weight-loss","healthy"],"difficulty":"easy","timeMinutes":20,"instructions": []},
  {"id":"soy-milk-smoothie","title":"Soy Milk Smoothie","description":"A delicious and authentic take on Soy Milk Smoothie.","ingredients":[{"name":"soy milk","quantity":"1 serving"},{"name":"banana","quantity":"1 serving"},{"name":"honey","quantity":"1 serving"},{"name":"oats","quantity":"1 serving"}],"equipment":["oven"],"instructions":["Preheat oven to 200°C (400°F). Prepare soy milk, banana, honey, oats.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],"tags":["balanced","healthy"],"difficulty":"easy","timeMinutes":25},
  { id: 'egg-fried-rice', title: 'Egg Fried Rice', description: 'A quick, savory pan meal for using up cooked rice and vegetables.', ingredients: [{ name: 'rice', quantity: '1 cup cooked' }, { name: 'egg', quantity: '2' }, { name: 'onion', quantity: '1/2, diced' }, { name: 'soy sauce', quantity: '1 tbsp' }, { name: 'bell pepper', quantity: '1/2, diced', optional: true }], equipment: ['pan', 'stove'], instructions: ['Warm the pan over medium heat and soften the onion and pepper.', 'Push vegetables aside, add beaten eggs, and scramble until just set.', 'Add rice and soy sauce. Toss until hot and evenly coated, then serve.'], tags: ['balanced', 'high-protein'], difficulty: 'easy', timeMinutes: 15 },
  { id: 'chicken-rice-bowl', title: 'Lemon Chicken Rice Bowl', description: 'Bright, filling chicken with rice and fresh vegetables.', ingredients: [{ name: 'chicken', quantity: '1 breast, sliced' }, { name: 'rice', quantity: '1 cup cooked' }, { name: 'lemon', quantity: '1/2' }, { name: 'tomato', quantity: '1, chopped' }, { name: 'spinach', quantity: '1 handful' }], equipment: ['pan', 'stove'], instructions: ['Season chicken and cook in a hot pan until golden and cooked through.', 'Add spinach to the pan for the final minute to wilt.', 'Serve over rice with tomato and a squeeze of lemon.'], tags: ['healthy', 'high-protein', 'balanced'], difficulty: 'easy', timeMinutes: 20 },
  { id: 'tomato-pasta', title: 'One-Pan Tomato Pasta', description: 'Comforting pantry pasta with a simple tomato sauce.', ingredients: [{ name: 'pasta', quantity: '100 g' }, { name: 'tomato', quantity: '2, chopped' }, { name: 'onion', quantity: '1/2, diced' }, { name: 'cheese', quantity: '2 tbsp, grated', optional: true }], equipment: ['pot', 'stove'], instructions: ['Boil pasta in salted water until tender, then reserve a little cooking water.', 'Soften onion and tomatoes in the pot with a splash of cooking water.', 'Toss pasta through the sauce and finish with cheese if using.'], tags: ['balanced', 'healthy'], difficulty: 'easy', timeMinutes: 25 },
  { id: 'bean-toast', title: 'Smoky Beans on Toast', description: 'A fast, hearty meal with pantry beans and crisp toast.', ingredients: [{ name: 'beans', quantity: '1 cup, drained' }, { name: 'tomato', quantity: '1, chopped' }, { name: 'onion', quantity: '1/2, diced' }, { name: 'bread', quantity: '2 slices' }, { name: 'cheese', quantity: '1 tbsp', optional: true }], equipment: ['pan', 'stove'], instructions: ['Cook onion and tomato in a pan until soft.', 'Stir in beans and warm for five minutes, lightly crushing some beans.', 'Toast the bread and spoon beans over it.'], tags: ['healthy', 'balanced'], difficulty: 'easy', timeMinutes: 15 },
  { id: 'banana-oat-smoothie', title: 'Banana Oat Smoothie', description: 'A creamy breakfast blended in minutes.', ingredients: [{ name: 'banana', quantity: '1' }, { name: 'oats', quantity: '1/3 cup' }, { name: 'yogurt', quantity: '1/2 cup' }], equipment: ['blender'], instructions: ['Add banana, oats, yogurt, and a splash of water to a blender.', 'Blend until smooth and pour into a glass.'], tags: ['healthy', 'high-protein'], difficulty: 'easy', timeMinutes: 5 },
  { id: 'spinach-omelet', title: 'Spinach Omelet', description: 'Soft eggs with wilted spinach and melted cheese.', ingredients: [{ name: 'egg', quantity: '2' }, { name: 'spinach', quantity: '1 handful' }, { name: 'cheese', quantity: '2 tbsp' }], equipment: ['pan', 'stove'], instructions: ['Wilt spinach in a lightly greased pan.', 'Pour in beaten eggs and cook until almost set.', 'Add cheese, fold the omelet, and cook until set.'], tags: ['high-protein', 'healthy'], difficulty: 'easy', timeMinutes: 10 },
  { id: 'microwave-egg-rice', title: 'Microwave Egg Rice Cup', description: 'A practical single-serving meal for kitchens without a stove.', ingredients: [{ name: 'rice', quantity: '1 cup cooked' }, { name: 'egg', quantity: '1' }, { name: 'soy sauce', quantity: '1 tsp' }, { name: 'onion', quantity: '1 tbsp, diced' }], equipment: ['microwave'], instructions: ['Mix rice, onion, and soy sauce in a microwave-safe bowl.', 'Make a well, crack in the egg, and cover loosely.', 'Microwave in short bursts until the egg is cooked through, stirring between bursts.'], tags: ['balanced', 'high-protein'], difficulty: 'easy', timeMinutes: 8 },
  { id: 'lentil-tomato-soup', title: 'Lentil Tomato Soup', description: 'A warm pot of lentils, tomato, and onion for an easy filling meal.', ingredients: [{ name: 'lentils', quantity: '1/2 cup' }, { name: 'tomato', quantity: '2, chopped' }, { name: 'onion', quantity: '1/2, diced' }, { name: 'garlic', quantity: '1 clove', optional: true }], equipment: ['pot', 'stove'], instructions: ['Rinse lentils and add them to a pot with tomato, onion, and water.', 'Simmer until the lentils are soft, stirring occasionally.', 'Season, mash lightly for body, and serve warm.'], tags: ['healthy', 'balanced'], difficulty: 'easy', timeMinutes: 30 },
  { id: 'chickpea-spinach-pan', title: 'Chickpea Spinach Pan', description: 'A quick skillet meal with chickpeas and greens.', ingredients: [{ name: 'chickpeas', quantity: '1 cup, drained' }, { name: 'spinach', quantity: '2 handfuls' }, { name: 'tomato', quantity: '1, chopped' }, { name: 'garlic', quantity: '1 clove', optional: true }], equipment: ['pan', 'stove'], instructions: ['Warm chickpeas and tomato in a pan.', 'Add spinach and cook until wilted.', 'Season and serve with toast or rice if available.'], tags: ['healthy', 'balanced'], difficulty: 'easy', timeMinutes: 15 },
  { id: 'tuna-rice-bowl', title: 'Tuna Rice Bowl', description: 'A fast pantry bowl with tuna, rice, and crunchy vegetables.', ingredients: [{ name: 'tuna', quantity: '1 can' }, { name: 'rice', quantity: '1 cup cooked' }, { name: 'cucumber', quantity: '1/2, chopped' }, { name: 'soy sauce', quantity: '1 tsp', optional: true }], equipment: ['microwave'], instructions: ['Warm the rice if needed.', 'Flake tuna over the rice and add cucumber.', 'Finish with soy sauce or lemon if available.'], tags: ['high-protein', 'balanced'], difficulty: 'easy', timeMinutes: 7 },
  { id: 'potato-egg-hash', title: 'Potato Egg Hash', description: 'Crisp potatoes with egg and onion for a simple pan meal.', ingredients: [{ name: 'potato', quantity: '1 medium, diced' }, { name: 'egg', quantity: '2' }, { name: 'onion', quantity: '1/2, sliced' }], equipment: ['pan', 'stove'], instructions: ['Cook potato cubes in a pan until tender and golden.', 'Add onion and cook until soft.', 'Crack in eggs and cook until set.'], tags: ['balanced', 'high-protein'], difficulty: 'easy', timeMinutes: 22 },
  { id: 'banana-peanut-oats', title: 'Banana Peanut Oats', description: 'Warm oats with banana and peanut butter.', ingredients: [{ name: 'oats', quantity: '1/2 cup' }, { name: 'banana', quantity: '1' }, { name: 'milk', quantity: '1 cup' }, { name: 'peanut butter', quantity: '1 tbsp' }], equipment: ['pot', 'stove'], instructions: ['Simmer oats and milk until creamy.', 'Stir in sliced banana.', 'Top with peanut butter and serve.'], tags: ['balanced', 'high-protein'], difficulty: 'easy', timeMinutes: 10 },
  { id: 'microwave-potato-beans', title: 'Microwave Potato Beans', description: 'A no-stove bowl with potato, beans, and tomato.', ingredients: [{ name: 'potato', quantity: '1 medium' }, { name: 'beans', quantity: '1/2 cup' }, { name: 'tomato', quantity: '1, chopped' }, { name: 'cheese', quantity: '1 tbsp', optional: true }], equipment: ['microwave'], instructions: ['Pierce potato and microwave until tender.', 'Warm beans and tomato separately.', 'Split potato, spoon beans over it, and add cheese if using.'], tags: ['balanced', 'healthy'], difficulty: 'easy', timeMinutes: 12 },
  { id: 'tofu-broccoli-rice', title: 'Tofu Broccoli Rice', description: 'A plant-forward rice bowl with tofu and broccoli.', ingredients: [{ name: 'tofu', quantity: '150 g, cubed' }, { name: 'broccoli', quantity: '1 cup' }, { name: 'rice', quantity: '1 cup cooked' }, { name: 'soy sauce', quantity: '1 tbsp' }], equipment: ['pan', 'stove'], instructions: ['Brown tofu cubes in a pan.', 'Add broccoli with a splash of water and cover briefly.', 'Serve over rice with soy sauce.'], tags: ['healthy', 'high-protein'], difficulty: 'easy', timeMinutes: 18 },
  { id: 'vegetable-omelet-wrap', title: 'Vegetable Omelet Wrap', description: 'Eggs and vegetables folded into a tortilla.', ingredients: [{ name: 'egg', quantity: '2' }, { name: 'tortilla', quantity: '1' }, { name: 'bell pepper', quantity: '1/2, sliced' }, { name: 'spinach', quantity: '1 handful' }], equipment: ['pan', 'stove'], instructions: ['Cook pepper and spinach until softened.', 'Add beaten eggs and cook until set.', 'Slide into a tortilla and fold.'], tags: ['high-protein', 'balanced'], difficulty: 'easy', timeMinutes: 12 },
  { id: 'avocado-egg-toast', title: 'Avocado Egg Toast', description: 'Toast topped with mashed avocado and egg.', ingredients: [{ name: 'bread', quantity: '2 slices' }, { name: 'avocado', quantity: '1/2' }, { name: 'egg', quantity: '1' }, { name: 'lemon', quantity: '1 squeeze', optional: true }], equipment: ['pan', 'stove'], instructions: ['Toast the bread in a dry pan.', 'Cook the egg to your liking.', 'Mash avocado on toast and top with egg.'], tags: ['healthy', 'balanced'], difficulty: 'easy', timeMinutes: 10 },
  { id: 'chicken-spinach-pasta', title: 'Chicken Spinach Pasta', description: 'A simple high-protein pasta with chicken and greens.', ingredients: [{ name: 'chicken', quantity: '1 breast, sliced' }, { name: 'pasta', quantity: '100 g' }, { name: 'spinach', quantity: '1 handful' }, { name: 'cheese', quantity: '2 tbsp', optional: true }], equipment: ['pot', 'pan', 'stove'], instructions: ['Boil pasta until tender.', 'Cook chicken in a pan until done.', 'Toss pasta, chicken, spinach, and cheese together.'], tags: ['high-protein', 'balanced'], difficulty: 'easy', timeMinutes: 25 },
  { id: 'tomato-egg-drop-soup', title: 'Tomato Egg Drop Soup', description: 'A light soup with tomato ribbons and egg.', ingredients: [{ name: 'tomato', quantity: '2, chopped' }, { name: 'egg', quantity: '1' }, { name: 'onion', quantity: '2 tbsp, diced', optional: true }], equipment: ['pot', 'stove'], instructions: ['Simmer tomato and onion in water until softened.', 'Beat the egg and stream it into the simmering soup.', 'Stir gently, season, and serve.'], tags: ['healthy', 'weight-loss'], difficulty: 'easy', timeMinutes: 15 },
  { id: 'broccoli-cheese-rice', title: 'Broccoli Cheese Rice', description: 'Comforting rice with broccoli and a little cheese.', ingredients: [{ name: 'rice', quantity: '1 cup cooked' }, { name: 'broccoli', quantity: '1 cup' }, { name: 'cheese', quantity: '2 tbsp' }], equipment: ['microwave'], instructions: ['Microwave broccoli with a splash of water until tender.', 'Stir in rice and warm through.', 'Add cheese and microwave briefly until melted.'], tags: ['balanced'], difficulty: 'easy', timeMinutes: 9 },
  { id: 'chickpea-cucumber-salad', title: 'Chickpea Cucumber Salad', description: 'A cool no-cook bowl with chickpeas and vegetables.', ingredients: [{ name: 'chickpeas', quantity: '1 cup, drained' }, { name: 'cucumber', quantity: '1/2, chopped' }, { name: 'tomato', quantity: '1, chopped' }, { name: 'lemon', quantity: '1/2' }], equipment: [], instructions: ['Combine chickpeas, cucumber, and tomato in a bowl.', 'Squeeze lemon over the top.', 'Season, toss, and serve.'], tags: ['healthy', 'weight-loss', 'balanced'], difficulty: 'easy', timeMinutes: 8 },
  { id: 'paneer-pepper-pan', title: 'Paneer Pepper Pan', description: 'Paneer and peppers cooked quickly in one pan.', ingredients: [{ name: 'paneer', quantity: '150 g, cubed' }, { name: 'bell pepper', quantity: '1, sliced' }, { name: 'onion', quantity: '1/2, sliced' }, { name: 'tomato', quantity: '1, chopped' }], equipment: ['pan', 'stove'], instructions: ['Brown paneer cubes in a hot pan.', 'Add onion, pepper, and tomato.', 'Cook until vegetables soften and serve warm.'], tags: ['high-protein', 'balanced'], difficulty: 'easy', timeMinutes: 18 },
  { id: 'mushroom-spinach-toast', title: 'Mushroom Spinach Toast', description: 'Savory mushrooms and spinach piled on toast.', ingredients: [{ name: 'mushroom', quantity: '1 cup, sliced' }, { name: 'spinach', quantity: '1 handful' }, { name: 'bread', quantity: '2 slices' }, { name: 'garlic', quantity: '1 clove', optional: true }], equipment: ['pan', 'stove'], instructions: ['Toast bread in a dry pan and set aside.', 'Cook mushrooms until browned.', 'Add spinach, cook until wilted, and spoon over toast.'], tags: ['healthy', 'balanced'], difficulty: 'easy', timeMinutes: 14 },
  { id: 'corn-pea-rice', title: 'Corn Pea Rice', description: 'A colorful rice dish with quick vegetables.', ingredients: [{ name: 'rice', quantity: '1 cup cooked' }, { name: 'corn', quantity: '1/2 cup' }, { name: 'peas', quantity: '1/2 cup' }, { name: 'onion', quantity: '2 tbsp, diced' }], equipment: ['pan', 'stove'], instructions: ['Cook onion in a pan until soft.', 'Add corn and peas and warm through.', 'Stir in rice and cook until hot.'], tags: ['balanced', 'healthy'], difficulty: 'easy', timeMinutes: 12 },
  { id: 'chicken-lettuce-wraps', title: 'Chicken Lettuce Wraps', description: 'Light lettuce cups with chicken and vegetables.', ingredients: [{ name: 'chicken', quantity: '1 breast, minced or sliced small' }, { name: 'lettuce', quantity: '4 leaves' }, { name: 'carrot', quantity: '1, grated' }, { name: 'soy sauce', quantity: '1 tbsp' }], equipment: ['pan', 'stove'], instructions: ['Cook chicken in a pan until browned and cooked through.', 'Stir in carrot and soy sauce.', 'Spoon into lettuce leaves and serve.'], tags: ['high-protein', 'weight-loss'], difficulty: 'easy', timeMinutes: 18 },
  { id: 'apple-yogurt-oats', title: 'Apple Yogurt Oats', description: 'A no-cook bowl with oats, apple, and yogurt.', ingredients: [{ name: 'oats', quantity: '1/2 cup' }, { name: 'yogurt', quantity: '1/2 cup' }, { name: 'apple', quantity: '1, chopped' }, { name: 'honey', quantity: '1 tsp', optional: true }], equipment: [], instructions: ['Stir oats and yogurt together.', 'Top with chopped apple.', 'Add honey if using and let sit for a few minutes.'], tags: ['healthy', 'balanced'], difficulty: 'easy', timeMinutes: 5 },
  { id: 'bean-cheese-wrap', title: 'Bean Cheese Wrap', description: 'A filling tortilla wrap with warm beans and cheese.', ingredients: [{ name: 'beans', quantity: '1/2 cup' }, { name: 'tortilla', quantity: '1' }, { name: 'cheese', quantity: '2 tbsp' }, { name: 'tomato', quantity: '1/2, chopped', optional: true }], equipment: ['pan', 'stove'], instructions: ['Warm beans in a pan and lightly mash them.', 'Place beans and cheese in a tortilla.', 'Fold and warm seam-side down until the tortilla is lightly crisp.'], tags: ['balanced', 'high-protein'], difficulty: 'easy', timeMinutes: 10 },
  { id: 'cabbage-egg-stir-fry', title: 'Cabbage Egg Stir-Fry', description: 'A fast, light pan meal with cabbage and egg.', ingredients: [{ name: 'cabbage', quantity: '2 cups, sliced' }, { name: 'egg', quantity: '2' }, { name: 'soy sauce', quantity: '1 tsp' }, { name: 'garlic', quantity: '1 clove', optional: true }], equipment: ['pan', 'stove'], instructions: ['Cook cabbage in a hot pan until tender-crisp.', 'Push cabbage aside and scramble the eggs.', 'Add soy sauce and toss together.'], tags: ['healthy', 'weight-loss', 'high-protein'], difficulty: 'easy', timeMinutes: 12 },
  { id: 'oven-potato-chicken', title: 'Oven Potato Chicken', description: 'A simple tray bake with chicken, potato, and onion.', ingredients: [{ name: 'chicken', quantity: '1 breast' }, { name: 'potato', quantity: '1 medium, chopped' }, { name: 'onion', quantity: '1/2, sliced' }, { name: 'lemon', quantity: '1/2', optional: true }], equipment: ['oven'], instructions: ['Place chicken, potato, and onion on a baking tray.', 'Bake until potato is tender and chicken is cooked through.', 'Finish with lemon if available.'], tags: ['high-protein', 'balanced'], difficulty: 'easy', timeMinutes: 35 },
  { id: 'blender-tomato-soup', title: 'Blender Tomato Soup', description: 'A smooth tomato soup with pantry aromatics.', ingredients: [{ name: 'tomato', quantity: '3, chopped' }, { name: 'onion', quantity: '1/2' }, { name: 'garlic', quantity: '1 clove', optional: true }, { name: 'yogurt', quantity: '1 tbsp', optional: true }], equipment: ['pot', 'stove', 'blender'], instructions: ['Simmer tomato, onion, and garlic until soft.', 'Blend carefully until smooth.', 'Warm again and swirl in yogurt if using.'], tags: ['healthy', 'weight-loss'], difficulty: 'easy', timeMinutes: 22 },
  { id: 'tofu-cabbage-wrap', title: 'Tofu Cabbage Wrap', description: 'A crisp wrap with tofu and cabbage.', ingredients: [{ name: 'tofu', quantity: '150 g, sliced' }, { name: 'cabbage', quantity: '1 cup, shredded' }, { name: 'tortilla', quantity: '1' }, { name: 'soy sauce', quantity: '1 tsp' }], equipment: ['pan', 'stove'], instructions: ['Brown tofu slices in a pan.', 'Toss cabbage with soy sauce.', 'Fill tortilla with tofu and cabbage, then fold.'], tags: ['healthy', 'high-protein'], difficulty: 'easy', timeMinutes: 14 },
  { id: 'carrot-pea-pasta', title: 'Carrot Pea Pasta', description: 'A simple vegetable pasta with common freezer staples.', ingredients: [{ name: 'pasta', quantity: '100 g' }, { name: 'carrot', quantity: '1, diced' }, { name: 'peas', quantity: '1/2 cup' }, { name: 'cheese', quantity: '1 tbsp', optional: true }], equipment: ['pot', 'stove'], instructions: ['Boil pasta and add carrot for the final few minutes.', 'Stir in peas until hot.', 'Drain and finish with cheese if using.'], tags: ['balanced', 'healthy'], difficulty: 'easy', timeMinutes: 18 },
  { id: 'chicken-corn-soup', title: 'Chicken Corn Soup', description: 'A gentle soup with chicken, corn, and egg ribbons.', ingredients: [{ name: 'chicken', quantity: '1/2 breast, shredded' }, { name: 'corn', quantity: '1/2 cup' }, { name: 'egg', quantity: '1' }, { name: 'onion', quantity: '2 tbsp, diced', optional: true }], equipment: ['pot', 'stove'], instructions: ['Simmer chicken, corn, and onion in water until hot.', 'Stream in beaten egg while stirring.', 'Season and serve warm.'], tags: ['high-protein', 'healthy'], difficulty: 'easy', timeMinutes: 20 },
  { id: 'peanut-banana-smoothie', title: 'Peanut Banana Smoothie', description: 'A richer smoothie with banana, milk, and peanut butter.', ingredients: [{ name: 'banana', quantity: '1' }, { name: 'milk', quantity: '1 cup' }, { name: 'peanut butter', quantity: '1 tbsp' }, { name: 'oats', quantity: '2 tbsp', optional: true }], equipment: ['blender'], instructions: ['Add banana, milk, and peanut butter to a blender.', 'Add oats if you want a thicker smoothie.', 'Blend until smooth.'], tags: ['high-protein', 'balanced'], difficulty: 'easy', timeMinutes: 5 },
  { id: 'tomato-paneer-rice', title: 'Tomato Paneer Rice', description: 'Rice tossed with paneer and tomato for a quick bowl.', ingredients: [{ name: 'rice', quantity: '1 cup cooked' }, { name: 'paneer', quantity: '100 g, cubed' }, { name: 'tomato', quantity: '1, chopped' }, { name: 'onion', quantity: '2 tbsp, diced' }], equipment: ['pan', 'stove'], instructions: ['Brown paneer in a pan and set aside.', 'Cook tomato and onion until soft.', 'Add rice and paneer, then toss until hot.'], tags: ['high-protein', 'balanced'], difficulty: 'easy', timeMinutes: 16 },
  { id: 'mushroom-egg-rice', title: 'Mushroom Egg Rice', description: 'A savory rice pan with mushrooms and egg.', ingredients: [{ name: 'rice', quantity: '1 cup cooked' }, { name: 'mushroom', quantity: '1 cup, sliced' }, { name: 'egg', quantity: '1' }, { name: 'soy sauce', quantity: '1 tsp' }], equipment: ['pan', 'stove'], instructions: ['Brown mushrooms in a pan.', 'Add rice and soy sauce and stir until hot.', 'Scramble in the egg and serve.'], tags: ['balanced', 'high-protein'], difficulty: 'easy', timeMinutes: 12 },
  { id: 'coconut-lentil-rice', title: 'Coconut Lentil Rice', description: 'Creamy lentils served over rice.', ingredients: [{ name: 'lentils', quantity: '1/2 cup' }, { name: 'coconut milk', quantity: '1/2 cup' }, { name: 'rice', quantity: '1 cup cooked' }, { name: 'tomato', quantity: '1, chopped' }], equipment: ['pot', 'stove'], instructions: ['Simmer lentils and tomato until lentils are soft.', 'Stir in coconut milk and warm gently.', 'Serve over cooked rice.'], tags: ['balanced', 'healthy'], difficulty: 'easy', timeMinutes: 28 },
];

// Assigns local, static photos downloaded specifically for each recipe.
export const recipeImages: Record<string, string> = {};
for (const recipe of recipes) {
  recipeImages[recipe.id] = `/images/${recipe.id}.jpg`;
}

export const detailedInstructions: Record<string, string[]> = {
  "zucchini-noodle-salad": ["Spiralize or thinly slice the zucchini into noodles.","Toss the zucchini with diced tomatoes and fresh basil.","Squeeze lemon over the top and season with salt and pepper.","Serve immediately for maximum crunch."],
  'paneer-tikka-masala': ["Prepare paneer, tomato, yogurt, garam masala. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'dal-tadka': ["Prepare lentils, onion, cumin, garlic. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'aloo-gobi': ["Preheat oven to 200°C (400°F). Prepare potato, broccoli, turmeric, cumin.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'palak-paneer': ["Prepare spinach, paneer, garlic, cream. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'chana-masala': ["Prepare chickpeas, tomato, onion, garam masala. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'jeera-rice': ["Prepare rice, cumin, butter, coriander. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'egg-curry': ["Preheat oven to 200°C (400°F). Prepare egg, tomato, onion, garam masala.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'baingan-bharta': ["Prepare eggplant, tomato, onion, garlic. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'mushroom-matar': ["Prepare mushroom, peas, onion, tomato. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'chicken-korma': ["Prepare chicken, yogurt, onion, coriander. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'fish-curry': ["Preheat oven to 200°C (400°F). Prepare salmon, tomato, coconut milk, turmeric.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'vegetable-biryani': ["Prepare rice, carrot, beans, garam masala. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'bhindi-masala': ["Prepare zucchini, onion, tomato, cumin. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'rajma': ["Prepare beans, tomato, onion, garam masala. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'chicken-madras': ["Preheat oven to 200°C (400°F). Prepare chicken, chili powder, tomato, mustard seeds.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'prawn-curry': ["Prepare shrimp, coconut milk, onion, turmeric. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'tofu-tikka': ["Prepare tofu, yogurt, garam masala, onion. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'aloo-matar': ["Prepare potato, peas, tomato, cumin. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'matar-paneer': ["Preheat oven to 200°C (400°F). Prepare paneer, peas, tomato, garam masala.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'keema-matar': ["Prepare beef, peas, onion, tomato. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'chicken-65': ["Prepare chicken, yogurt, chili powder, garlic. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'dal-makhani': ["Prepare lentils, beans, butter, cream. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'south-indian-lemon-rice': ["Preheat oven to 200°C (400°F). Prepare rice, lemon, mustard seeds, peanut butter.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'chicken-chettinad': ["Prepare chicken, coconut milk, coriander, chili powder. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  "turkey-lettuce-wraps": ["Sauté the minced chicken and onion until browned.","Add the soy sauce and cook until the liquid evaporates.","Spoon the mixture into the fresh lettuce leaves.","Wrap and eat immediately."],
  'masala-omelette': ["Prepare egg, onion, tomato, chili powder. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'curd-rice': ["Preheat oven to 200°C (400°F). Prepare rice, yogurt, mustard seeds, cucumber.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'sweet-potato-tikki': ["Prepare sweet potato, cumin, coriander, bread. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'chicken-tikka-salad': ["Prepare chicken, lettuce, yogurt, cucumber. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  "spicy-tomato-broth": ["Boil the tomato puree with 2 cups of water.","Add the garlic and chili powder and simmer for 10 minutes.","Garnish with fresh coriander just before serving.","Serve very hot."],
  'paneer-bhurji': ["Preheat oven to 200°C (400°F). Prepare paneer, onion, tomato, bell pepper.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'spaghetti-bolognese': ["Prepare pasta, beef, tomato, onion. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  "cauliflower-rice-bowl": ["Finely chop the cabbage to resemble rice grains.","Sauté the cabbage and chicken until the chicken is cooked through.","Add spinach at the very end until just wilted.","Squeeze lemon juice over the bowl and serve hot."],
  'caprese-salad': ["Prepare tomato, mozzarella, basil, lemon. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'beef-tacos': ["Preheat oven to 200°C (400°F). Prepare beef, tortilla, cheese, tomato.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'chicken-fajitas': ["Prepare chicken, bell pepper, onion, tortilla. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  "broccoli-garlic-stir-fry": ["Heat a pan over high heat.","Sauté the garlic for 30 seconds until fragrant.","Add the broccoli and mushrooms with a splash of water and cover to steam for 3 minutes.","Add soy sauce, toss well, and serve."],
  'salmon-teriyaki': ["Prepare salmon, soy sauce, rice, broccoli. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'beef-stir-fry': ["Preheat oven to 200°C (400°F). Prepare beef, broccoli, soy sauce, garlic.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'margherita-pizza-toast': ["Prepare bread, tomato, mozzarella, basil. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'chicken-caesar-salad': ["Prepare chicken, lettuce, cheese, bread. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  "cucumber-tomato-salad": ["Chop the cucumber, tomatoes, and onion.","Combine in a large bowl.","Drizzle with lemon juice and let sit for 2 minutes to meld flavors.","Serve fresh."],
  "lentil-cucumber-salad": ["Mix the cooked lentils with the diced cucumber and tomato.","Toss everything with a generous squeeze of lemon juice.","Let sit for 5 minutes before eating so the lentils absorb the dressing.","Serve cold or at room temperature."],
  'zucchini-noodles': ["Prepare zucchini, tomato, garlic, mozzarella. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'baked-salmon': ["Prepare salmon, lemon, garlic, sweet potato. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  "baked-lemon-cod": ["Preheat the oven to 200C (400F).","Place the fish and broccoli on a baking tray.","Top the fish with minced garlic and lemon slices.","Bake for 15-20 minutes until the fish flakes easily."],
  'chicken-parmesan': ["Preheat oven to 200°C (400°F). Prepare chicken, tomato, mozzarella, bread.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'beef-burger-bowls': ["Prepare beef, lettuce, tomato, cheese. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  "spinach-tofu-scramble": ["Crumble the tofu into a pan over medium heat.","Add turmeric for color and sauté for 3 minutes.","Stir in the tomato and spinach until the spinach wilts.","Serve hot."],
  'shrimp-fried-rice': ["Prepare rice, shrimp, egg, peas. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'tofu-pad-thai': ["Preheat oven to 200°C (400°F). Prepare pasta, tofu, egg, peanut butter.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'chicken-noodle-soup': ["Prepare chicken, pasta, carrot, onion. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'minestrone-soup': ["Prepare pasta, beans, tomato, zucchini. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'eggplant-parmesan': ["Prepare eggplant, tomato, mozzarella, cheese. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'greek-salad': ["Preheat oven to 200°C (400°F). Prepare cucumber, tomato, onion, cheese.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'chicken-quesadilla': ["Prepare chicken, tortilla, cheese, bell pepper. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'beef-burrito-bowl': ["Prepare beef, rice, beans, corn. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'shrimp-tacos': ["Prepare shrimp, tortilla, cabbage, lemon. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'pork-dumpling-bowl': ["Preheat oven to 200°C (400°F). Prepare pork, cabbage, rice, soy sauce.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'basil-pesto-pasta': ["Prepare pasta, basil, garlic, cheese. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  'tomato-basil-soup': ["Prepare tomato, basil, cream, garlic. Heat pan or pot over medium heat.","Cook aromatics and protein until browned.","Add remaining ingredients and simmer until flavors meld.","Serve hot."],
  "clear-cabbage-soup": ["Boil 3 cups of water in a pot.","Add all chopped vegetables and simmer.","Cook for 15 minutes until vegetables are extremely soft and the broth is flavorful.","Season gently and serve piping hot."],
  'soy-milk-smoothie': ["Preheat oven to 200°C (400°F). Prepare soy milk, banana, honey, oats.","Mix ingredients together and place in a baking dish.","Bake until cooked through and golden on top, about 25-30 minutes.","Let rest for 5 minutes before serving."],
  'egg-fried-rice': [
    'Break the cold cooked rice apart with your fingers or a spoon so there are no big clumps. Dice the onion and bell pepper before you turn on the stove.',
    'Put the pan on medium heat. Add a small spoon of oil if you have it, then cook the onion and bell pepper for 2 to 3 minutes, stirring often, until they smell sweet and look slightly soft.',
    'Beat the eggs in a small bowl with a pinch of salt. Push the vegetables to one side of the pan, pour in the eggs, and gently stir them for about 1 minute until they are just set.',
    'Add the rice to the pan. Press and toss it through the egg and vegetables for 2 to 3 minutes so the rice becomes hot all the way through.',
    'Pour soy sauce around the edge of the pan, then toss everything until the rice is evenly coated. Taste one spoonful and add a little more soy sauce only if it needs salt.',
    'Turn off the heat and serve right away while the rice is hot and the egg is still soft.',
  ],
  'chicken-rice-bowl': [
    'Slice the chicken into thin strips so it cooks quickly and evenly. Chop the tomato and wash the spinach before heating the pan.',
    'Warm the pan over medium heat with a small spoon of oil if available. Add the chicken in one layer and cook for 4 to 5 minutes, turning the pieces until no pink remains in the center.',
    'Squeeze lemon over the chicken and stir to loosen any browned bits from the pan. Add spinach and cook for about 1 minute until it wilts.',
    'Warm the cooked rice if it is cold. Spoon the rice into a bowl, then add the chicken and spinach on top.',
    'Add chopped tomato at the end so it stays fresh. Taste and add a pinch of salt, pepper, or more lemon if you like.',
  ],
  'tomato-pasta': [
    'Bring a pot of water to a boil, add a pinch of salt if you have it, and cook the pasta until it is tender but not mushy.',
    'Before draining, save a small cup of the pasta water. Drain the pasta and keep it nearby.',
    'In the same pot, cook onion and tomato over medium heat for 4 to 5 minutes until the tomato breaks down into a loose sauce.',
    'Add a splash of the saved pasta water and stir until the sauce looks glossy instead of dry.',
    'Add the pasta back to the pot and toss for 1 minute. Finish with cheese if using, then serve hot.',
  ],
  'bean-toast': [
    'Drain the beans if they are canned. Dice the onion and tomato so they cook down evenly.',
    'Heat the pan over medium heat. Cook onion for 2 minutes, then add tomato and cook for another 3 minutes until soft.',
    'Add the beans and a splash of water. Stir and lightly mash some beans with the spoon to make the mixture creamy.',
    'Simmer for 4 to 5 minutes until thick. Taste and season with salt, pepper, or a pinch of chili if you have it.',
    'Toast the bread in the pan or toaster. Spoon the hot beans over the toast and add cheese if using.',
  ],
  'banana-oat-smoothie': [
    'Peel the banana and break it into chunks so the blender can catch it easily.',
    'Add banana, oats, yogurt, and a splash of cold water or milk to the blender.',
    'Blend for 20 to 30 seconds. Stop and scrape the sides if oats stick near the top.',
    'If the smoothie is too thick, add another small splash of liquid and blend again.',
    'Pour into a glass and drink soon, while the texture is still smooth.',
  ],
  'spinach-omelet': [
    'Beat the eggs in a bowl with a pinch of salt until the yolks and whites are fully mixed.',
    'Warm a pan over medium-low heat. Add spinach and cook for 30 to 60 seconds until it wilts.',
    'Spread the spinach evenly, then pour in the eggs. Tilt the pan so the eggs cover the bottom.',
    'Cook gently for 2 to 3 minutes. When the top is mostly set but still shiny, add cheese to one side.',
    'Fold the omelet in half and cook for another 30 seconds. Slide it onto a plate before it becomes dry.',
  ],
  'microwave-egg-rice': [
    'Use a microwave-safe bowl with enough room for the rice to puff slightly. Mix rice, onion, and soy sauce together first.',
    'Make a small well in the center of the rice and crack the egg into it. Pierce the yolk once with a fork so it does not burst.',
    'Cover the bowl loosely with a microwave-safe plate or lid. Do not seal it tight.',
    'Microwave for 45 seconds, stir the rice around the egg, then microwave in 20-second bursts until the egg is set.',
    'Let the bowl stand for 1 minute because it will be very hot. Stir once more and taste before eating.',
  ],
  'lentil-tomato-soup': [
    'Rinse the lentils under running water until the water looks mostly clear.',
    'Add lentils, tomato, onion, garlic if using, and about 2 cups of water to a pot.',
    'Bring to a boil, then lower the heat so the soup gently bubbles. Stir every few minutes so lentils do not stick.',
    'Cook for 20 to 25 minutes, until the lentils are soft enough to mash against the side of the pot.',
    'Mash a few spoonfuls of lentils to thicken the soup, season to taste, and serve warm.',
  ],
  'chickpea-spinach-pan': [
    'Drain and rinse the chickpeas. Chop the tomato and mince garlic if you are using it.',
    'Heat a pan over medium heat and add garlic for 30 seconds, just until fragrant.',
    'Add tomato and chickpeas. Cook for 4 to 5 minutes, stirring, until the tomato softens and coats the chickpeas.',
    'Add spinach in handfuls. Stir until it wilts and turns bright green.',
    'Taste and season. Serve as a bowl, on toast, or over rice if you have cooked rice ready.',
  ],
  'tuna-rice-bowl': [
    'Warm the rice in the microwave until steaming, or use room-temperature rice if you prefer a cold bowl.',
    'Drain the tuna and flake it with a fork so it spreads through the rice easily.',
    'Chop cucumber into small pieces for crunch.',
    'Add rice, tuna, and cucumber to a bowl. Drizzle soy sauce over the top if using.',
    'Mix gently, taste, and add lemon or pepper if available.',
  ],
  'potato-egg-hash': [
    'Dice the potato into small cubes so it cooks faster. Slice the onion before heating the pan.',
    'Add potato to a pan over medium heat with a small spoon of oil and a pinch of salt. Cook for 8 to 10 minutes, stirring often.',
    'When the potato is browned outside and soft inside, add onion and cook for 3 minutes.',
    'Make two small spaces in the pan and crack in the eggs. Cover the pan if you have a lid.',
    'Cook until the egg whites are set. Serve straight from the pan or slide onto a plate.',
  ],
  'banana-peanut-oats': [
    'Add oats and milk to a small pot. Put it over medium-low heat and stir often.',
    'When the oats start to thicken, slice in the banana and stir so it softens into the porridge.',
    'Cook for 4 to 6 minutes total, adding a splash more milk or water if it gets too thick.',
    'Turn off the heat and stir in peanut butter until it melts through.',
    'Serve warm. Let it cool for a minute before eating because oats hold heat.',
  ],
  'microwave-potato-beans': [
    'Scrub the potato and pierce it several times with a fork.',
    'Microwave the potato for 4 minutes, turn it over, then microwave 3 to 5 minutes more until a knife slides in easily.',
    'In another microwave-safe bowl, mix beans and tomato. Microwave for 1 to 2 minutes until hot.',
    'Split the potato open carefully and fluff the inside with a fork.',
    'Spoon the beans over the potato and add cheese if using. Microwave 20 seconds more if you want the cheese melted.',
  ],
  'tofu-broccoli-rice': [
    'Pat the tofu dry with a towel, then cut it into bite-size cubes.',
    'Heat a pan over medium heat. Cook tofu for 4 to 5 minutes, turning pieces until at least two sides are lightly browned.',
    'Add broccoli and a small splash of water. Cover for 2 minutes so the broccoli steams.',
    'Remove the lid, add soy sauce, and stir until the broccoli is tender and the tofu is coated.',
    'Serve over warm rice and spoon any pan sauce over the top.',
  ],
  'vegetable-omelet-wrap': [
    'Slice the bell pepper thinly and wash the spinach. Beat the eggs in a bowl.',
    'Cook pepper in a pan over medium heat for 2 minutes, then add spinach and cook until wilted.',
    'Pour in the eggs and gently move them around the pan until just set.',
    'Warm the tortilla in the same pan for 20 seconds if you like it softer.',
    'Place the omelet on the tortilla, fold the sides in, and roll it into a wrap.',
  ],
  'avocado-egg-toast': [
    'Toast the bread in a dry pan until crisp on both sides, then move it to a plate.',
    'Mash avocado with a fork. Add lemon and a pinch of salt if available.',
    'Cook the egg in the pan to your preference: about 2 to 3 minutes for a soft yolk, longer for firm.',
    'Spread avocado over the toast and place the egg on top.',
    'Eat right away so the toast stays crisp.',
  ],
  'chicken-spinach-pasta': [
    'Boil pasta in salted water until tender. Save a small cup of pasta water before draining.',
    'Slice chicken thinly. Cook it in a pan over medium heat for 5 to 7 minutes until cooked through.',
    'Add spinach to the chicken pan and stir until wilted.',
    'Add drained pasta and a splash of pasta water. Toss until everything is glossy and hot.',
    'Add cheese if using, taste, and serve.',
  ],
  'tomato-egg-drop-soup': [
    'Chop tomatoes small so they soften quickly. Beat the egg in a cup or small bowl.',
    'Add tomato, onion if using, and about 1.5 cups of water to a pot. Simmer for 8 to 10 minutes.',
    'When the tomato looks soft and the broth is lightly red, lower the heat.',
    'Slowly pour in the beaten egg while stirring the soup in one direction. Thin egg ribbons will form.',
    'Cook 30 seconds more, season gently, and serve hot.',
  ],
  'broccoli-cheese-rice': [
    'Put broccoli in a microwave-safe bowl with a spoon of water. Cover loosely.',
    'Microwave for 1 to 2 minutes until the broccoli is bright green and tender.',
    'Add cooked rice and stir. Microwave for another 1 minute until the rice is hot.',
    'Sprinkle cheese over the top and microwave for 20 to 30 seconds until melted.',
    'Stir once, let it cool for a minute, and serve.',
  ],
  'chickpea-cucumber-salad': [
    'Drain and rinse the chickpeas, then add them to a bowl.',
    'Chop cucumber and tomato into bite-size pieces and add them to the chickpeas.',
    'Squeeze lemon over the bowl. Add a pinch of salt and pepper if you have them.',
    'Toss everything until the lemon coats the vegetables.',
    'Let it sit for 2 minutes before eating so the flavors settle.',
  ],
  'paneer-pepper-pan': [
    'Cut paneer into cubes and slice the pepper and onion before heating the pan.',
    'Warm a pan over medium heat. Brown paneer for 2 to 3 minutes, then move it to a plate.',
    'Add onion and pepper to the same pan and cook for 3 to 4 minutes until slightly soft.',
    'Add tomato and cook until it breaks down into a light sauce.',
    'Return paneer to the pan, toss gently, warm for 1 minute, and serve.',
  ],
  'mushroom-spinach-toast': [
    'Toast the bread in a dry pan until crisp, then set it on a plate.',
    'Slice mushrooms if they are not already sliced. Cook them in the pan over medium heat without crowding.',
    'Stir every minute until the mushrooms release moisture and then brown, about 5 minutes.',
    'Add garlic if using, then spinach. Cook until the spinach wilts.',
    'Spoon the mushroom-spinach mixture onto toast and eat while warm.',
  ],
  'corn-pea-rice': [
    'Warm a pan over medium heat and cook onion for 2 minutes until it softens.',
    'Add corn and peas. Stir for 2 to 3 minutes until they are hot.',
    'Add cooked rice and break up any clumps with the spoon.',
    'Cook for 2 more minutes, stirring, until the rice is hot all the way through.',
    'Taste and season with salt, pepper, or soy sauce if available.',
  ],
  'chicken-lettuce-wraps': [
    'Separate lettuce leaves carefully and keep them whole. Grate or thinly slice the carrot.',
    'Cut chicken into very small pieces so it cooks quickly and fits in the lettuce cups.',
    'Cook chicken in a pan over medium heat for 5 to 7 minutes until no pink remains.',
    'Add carrot and soy sauce, then stir for 1 minute so the carrot softens slightly.',
    'Spoon the hot chicken mixture into lettuce leaves and fold them like small wraps.',
  ],
  'apple-yogurt-oats': [
    'Chop the apple into small pieces so every bite has some fruit.',
    'Stir oats and yogurt together in a bowl until the oats are fully coated.',
    'Add the apple and honey if using.',
    'Let the bowl sit for 3 to 5 minutes so the oats soften slightly.',
    'Stir once more before eating. Add a splash of milk if you want it looser.',
  ],
  'bean-cheese-wrap': [
    'Warm beans in a pan over medium heat with a spoon of water so they do not dry out.',
    'Mash some of the beans with the back of a spoon until the filling looks thick.',
    'Place the tortilla flat and spoon beans down the center. Add cheese and tomato if using.',
    'Fold the sides inward, then roll the tortilla around the filling.',
    'Put the wrap back in the pan seam-side down for 1 to 2 minutes until lightly crisp.',
  ],
  'cabbage-egg-stir-fry': [
    'Slice cabbage thinly so it cooks quickly. Beat the eggs in a small bowl.',
    'Heat the pan over medium-high heat. Add cabbage and stir-fry for 3 to 4 minutes until tender but still a little crisp.',
    'Push cabbage to one side and pour eggs into the empty space.',
    'Stir the eggs until softly scrambled, then mix them through the cabbage.',
    'Add soy sauce, toss for 30 seconds, and serve hot.',
  ],
  'oven-potato-chicken': [
    'Heat the oven to 200 C or 400 F. Cut potato into small chunks so it finishes with the chicken.',
    'Place chicken, potato, and onion on a baking tray. Add a small spoon of oil and a pinch of salt if available.',
    'Spread everything in one layer so it roasts instead of steaming.',
    'Bake for 25 to 35 minutes, turning the potato once halfway through.',
    'The chicken is ready when the center is no longer pink and the juices look clear. Rest for 3 minutes before serving.',
  ],
  'blender-tomato-soup': [
    'Chop tomato and onion. Add them to a pot with garlic if using and about 1 cup of water.',
    'Simmer for 12 to 15 minutes until the onion is soft and the tomato has collapsed.',
    'Let the soup cool for 2 minutes before blending. Blend carefully, holding the lid down with a towel.',
    'Pour the soup back into the pot and warm it gently.',
    'Taste, season, and swirl in yogurt if using. Do not boil hard after adding yogurt.',
  ],
  'tofu-cabbage-wrap': [
    'Pat tofu dry and slice it into strips. Shred the cabbage thinly.',
    'Cook tofu in a pan over medium heat for 3 to 4 minutes per side until lightly browned.',
    'Toss cabbage with soy sauce in a bowl, or warm it in the pan for 1 minute if you prefer it softer.',
    'Warm the tortilla briefly in the pan so it bends without tearing.',
    'Fill with tofu and cabbage, fold the sides in, and roll tightly.',
  ],
  'carrot-pea-pasta': [
    'Bring water to a boil in a pot. Add pasta and cook according to the package time.',
    'Add diced carrot during the last 4 minutes of pasta cooking so it softens.',
    'Add peas during the last 1 minute, just to heat them through.',
    'Drain everything, saving a spoon or two of pasta water.',
    'Return to the pot, add cheese if using, and stir with a splash of pasta water until lightly coated.',
  ],
  'chicken-corn-soup': [
    'Cut chicken into small pieces or use cooked shredded chicken if you already have it.',
    'Add chicken, corn, onion if using, and about 2 cups of water to a pot.',
    'Simmer until the chicken is cooked through and the corn is hot, about 10 to 12 minutes.',
    'Beat the egg in a cup. Slowly pour it into the soup while stirring to make thin ribbons.',
    'Cook 1 minute more, season gently, and serve hot.',
  ],
  'peanut-banana-smoothie': [
    'Peel the banana and break it into chunks.',
    'Add banana, milk, peanut butter, and oats if using to the blender.',
    'Blend for 20 to 30 seconds until smooth.',
    'If peanut butter sticks to the side, stop the blender, scrape it down, and blend again.',
    'Taste and add a splash more milk if you want a thinner smoothie.',
  ],
  'tomato-paneer-rice': [
    'Cut paneer into cubes and chop tomato and onion before heating the pan.',
    'Brown paneer in a pan over medium heat for 2 to 3 minutes, then set it aside.',
    'Cook onion and tomato in the same pan until the tomato turns saucy.',
    'Add cooked rice and stir until it is hot and coated with tomato.',
    'Return paneer to the pan, toss gently so it does not crumble too much, and serve.',
  ],
  'mushroom-egg-rice': [
    'Slice mushrooms and beat the egg in a small bowl.',
    'Cook mushrooms in a pan over medium heat until they release moisture and start to brown.',
    'Add cooked rice and soy sauce. Stir and press out clumps until the rice is hot.',
    'Push rice to one side, pour in the egg, and scramble until just set.',
    'Mix egg through the rice and serve immediately.',
  ],
  'coconut-lentil-rice': [
    'Rinse lentils well, then add them to a pot with tomato and about 1.5 cups of water.',
    'Bring to a boil, then lower the heat and simmer until the lentils are soft, about 20 minutes.',
    'Stir occasionally and add a splash of water if the pot looks dry before the lentils soften.',
    'Add coconut milk and simmer gently for 3 to 4 minutes. Do not boil hard after adding it.',
    'Spoon over warm rice and serve.',
  ],
};
